[tool.poetry]
name = "bluebuttonpy"
version = "0.1.0"
description = ""
authors = ["Srikanth Srungarapu <srikanth235@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
